Execution play with rework
simon-dube/CARMIN-server pull request #10
Opened 2018-04-17 15:44 UTC by simon-dube

This is a first very rough version of the execution play feature. We are merging it especially in the context of the release 0.0.1. More validation still needs to be done and an overall better management of the executions, but this still provides users with the possibility to run executions on their own machine (not in a container).

2018-04-17 23:31 UTC, louis-ver requested changes
Excellent work! Just a few things to change, and a few questions.

2018-04-17 23:31 UTC, louis-ver commented on server/config.py
> +    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URI')
Are we removing support for the default sqlite database?

2018-04-17 23:31 UTC, louis-ver commented on server/resources/decorators/__init__.py
>              if (errors):
Remove parantheses

2018-04-17 23:31 UTC, louis-ver commented on server/resources/execution_play.py
> +            print("invocation not valid")
Remove print

2018-04-17 23:31 UTC, louis-ver commented on server/resources/execution_play.py
> +        modified_inputs_path, error = create_relative_path_inputs(
Should check that the error is not null before continuing?

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/execution.py
> +    print("BEFORE PROCESS", file=sys.stderr)
Remove prints

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/execution.py
> +    print("user_data_dir: {}".format(user_data_dir), file=sys.stderr)
Remove prints

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/execution.py
> +    #2 Write the current execution pid to database
Is this a copy paste error? Not what you are doing

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/execution.py
> +    db.session.commit()
I'm not really familiar with SQLAlchemy, but do you need to `add` the execution here so that `commit()` applies the changes?

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/execution.py
> +    process.communicate()
`wait()` should be used instead of communicate since no communication is necessary. Also, proper cleanup must be added simply with `process.kill()` immediately after `process.wait()`

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/executions.py
> +def write_relative_path_inputs_to_file(
Once the execution has been launched, the relative inputs file should be deleted, since it leaks absolute path information.

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/executions.py
> +def write_relative_path_inputs_to_file(
The paths are absolute, not relative. Please rename the function

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/executions.py
> +def create_relative_path_inputs(username: str, execution_identifier: str,
The paths are absolute, not relative. Should also be renamed

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/pipelines.py
> +def get_pipeline_path(pipeline_identifier: str) -> str:
This should be refactored into `get_pipeline`, with an option to return a path

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/pipelines.py
> +def get_boutiques_descriptor_path(
This can be renamed to be more general, for when we support other descriptors. `get_original_descriptor_path` would do.

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/pipelines.py
> +        carmin_descriptor_path.name[:carmin_descriptor_path.name.index("_")],
Could you set these as variables. Took me a while to understand what was going on here. Something like:
```
descriptor_type = carmin_descriptor_path.name[:carmin_descriptor_path.name.index("_")]
original_descriptor_name = carmin_descriptor_path.name[carmin_descriptor_path.name.index("_") + 1:]
```
This would help readability

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/pipelines.py
> +def get_boutiques_descriptor(pipeline_path: str) -> (any, ErrorCodeAndMessage):
Could also be renamed to something more general

2018-04-17 23:31 UTC, louis-ver commented on server/resources/helpers/pipelines.py
> +        bosh(["export", "carmin", pipeline.path, carmin_pipeline])
Does `export` throw any errors? What do we do in the event that a descriptor is not valid?

2018-04-18 00:43 UTC, simon-dube commented on server/config.py
> +    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URI')
I believe it would be a better idea, otherwise, it might lead to unclear situations for the user what data source is used.

2018-04-18 00:51 UTC, simon-dube commented on server/resources/helpers/execution.py
> +    db.session.commit()
No this is the ways to do it. (Source: https://stackoverflow.com/questions/6699360/flask-sqlalchemy-update-a-rows-information)

2018-04-18 01:08 UTC, simon-dube commented on server/resources/helpers/executions.py
> +def write_relative_path_inputs_to_file(
Regarding the file deletion, I am not sure at which point it is safe to assume Boutiques actually read the file. I am hesitant to write a delete right after the Popen process is launched.

2018-04-18 01:23 UTC, simon-dube commented on server/resources/helpers/pipelines.py
> +        bosh(["export", "carmin", pipeline.path, carmin_pipeline])
For now I based myself on the fact that the output file will not be produced, but I will see with Tristan on how the boutiques code manages this case.

2018-04-18 01:59 UTC, louis-ver approved these changes

2018-04-18 02:58 UTC, merged